### ISSUE TITLE
Checks for other class id unused in BaseTrainer

### ISSUE THREAD

**Issue by agsedova** [knodle/knodle#276]

**Comment by marina-sp** [comment]
There is a [check](https://github.com/knodle/knodle/blob/develop/knodle/trainer/utils/checks.py) introduced to set the other class id if filtering is disabled. It makes sense to check it in the BaseTrainer, since these parameters are first introduced in the BaseTrainerConfig. 

However, the following points make me unsure about this:

- BaseTrainerConfig is the default config for the [Trainer ](https://github.com/knodle/knodle/blob/453df57420812b3b64406dcac5d0dfbac6cbd1e3/knodle/trainer/trainer.py#L56) class, not the BaseTrainer
- The __init__ function in the [BaseTrainer](https://github.com/knodle/knodle/blob/453df57420812b3b64406dcac5d0dfbac6cbd1e3/knodle/trainer/trainer.py#L80) is absent (probably because there was no use for it?)

My suggestion would be to bring back the __init__ of the BaseTrainer and perform the check there. Alternatively, it could be also done in the Trainer (because it defaults to BaseTrainerConfig) or even the MajorityTrainer (because we actually use other class and filtering there). 

What do you think @AndSt @agsedova?
